### ISSUE TITLE
make signup api functionality

### ISSUE THREAD

**Issue by isjxique** [akhan118/shelter-API#3]

**Comment by TechnoSayge** [comment]
Google API? Facebook?  Custom sign up api?

**Comment by TechnoSayge** [comment]
Doing some research...I found a video [https://youtu.be/xrdC222CO0U](url) and it details the steps and I want to make sure this works for us:

1. create api module using GII
2.  set that module in main.php
3.  create controller & model for api

So @ish256 it looks like you crated the api module already?  Located at [https://github.com/akhan118/shelter-API/blob/master/backend/modules/v1/controllers/ApiController.php](url)? 

Are my assumptions correct? @akhan118 @anguess

**Comment by isjxique** [comment]
yes this endpoint has been created.
